### ISSUE TITLE
Incorrect v1.0.1 release tag

### ISSUE THREAD

**Issue by nickdademo** [fix8mt/conjure_enum#13]
Great work on this library! :)

https://github.com/fix8mt/conjure_enum/releases/tag/v1.0.0
-> Tagged as `v1.0.0` but the release title and description states `v1.0.1`

Would be good to fix before merging this: https://github.com/microsoft/vcpkg/pull/40005

**Comment by dakka** [comment]
Updated tag

**Comment by dakka** [comment]
Hi - thanks for doing the package to vcpkg. What is the process if I want to update it? Is it just update the package artifacts from my fork of vcpkg and do PR? So change the version and hash?
cheers

**Comment by nickdademo** [comment]
> Hi - thanks for doing the package to vcpkg. What is the process if I want to update it? Is it just update the package artifacts from my fork of vcpkg and do PR? So change the version and hash? cheers

That's basically it :) Just remember when done to run `vcpkg x-add-version conjure-enum` and commit the result.
